# This script is for decrypting and revealing the password generated by the Generate&EncryptCredsByInput.ps1 script (which encrypted the password in the first place)
$encryptedPassword = get-content "\\ABC-app01\Public\Creds\ABCCredentials.txt"
$secureString = convertto-securestring -string ($encryptedPassword)
$bstr = SecureStringTOBSTR($secureString)
[System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr) } Out-String
